extends: theme-check:recommended
ValidSchemaName:
  exclude:
    - skeleton/**
MissingTemplate:
  exclude:
    - skeleton/**
MissingAsset:
  exclude:
    - skeleton/**
TranslationKeyExists:
  exclude:
    - skeleton/**
UndefinedObject:
  exclude:
    - skeleton/**
MatchingTranslations:
  enabled: false
TemplateLength:
  enabled: false
